create table greeting (id integer not null, content varchar(255) not null, primary key (id)) engine=InnoDB;
create table greeting_seq (next_val bigint) engine=InnoDB;
insert into greeting_seq values ( 1 );
create table hello_message_seq (next_val bigint) engine=InnoDB;
insert into hello_message_seq values ( 1 );
create table hello_message (id integer not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table greeting (id integer not null, content varchar(255) not null, primary key (id)) engine=InnoDB;
create table greeting_seq (next_val bigint) engine=InnoDB;
insert into greeting_seq values ( 1 );
create table hello_message_seq (next_val bigint) engine=InnoDB;
insert into hello_message_seq values ( 1 );
create table hello_message (id integer not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table greeting (id integer not null, content varchar(255) not null, primary key (id)) engine=InnoDB;
create table greeting_seq (next_val bigint) engine=InnoDB;
insert into greeting_seq values ( 1 );
create table hello_message_seq (next_val bigint) engine=InnoDB;
insert into hello_message_seq values ( 1 );
create table hello_message (id integer not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table greeting (id integer not null, content varchar(255) not null, primary key (id)) engine=InnoDB;
create table greeting_seq (next_val bigint) engine=InnoDB;
insert into greeting_seq values ( 1 );
create table hello_message_seq (next_val bigint) engine=InnoDB;
insert into hello_message_seq values ( 1 );
create table hello_message (id integer not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table greeting (id integer not null, content varchar(255) not null, primary key (id)) engine=InnoDB;
create table greeting_seq (next_val bigint) engine=InnoDB;
insert into greeting_seq values ( 1 );
create table hello_message_seq (next_val bigint) engine=InnoDB;
insert into hello_message_seq values ( 1 );
create table hello_message (id integer not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
